"use client";
// ─── Articles — every client's articles on one sheet ─────────────────────────
// The answer to "how many are pending?" without opening ten projects. A week's
// articles are three separate tasks under a weekly parent, so the board can
// only ever show one client's week at a time; this flattens all of them into
// one row per article with a per-client outstanding count on top.
//
// A task appears here once it is ticked in the Article column on a project's
// Sheet tab (or generated by the weekly SEO engine, which marks its own).
// Nothing is ever inferred from a title.
//
// Visible to staff as well as the admin, scoped to the projects they can see —
// the same rule the projects list uses. Articles are delivery data, not money
// (see the Owner-Only Financial Data rule).

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Topbar } from "@/components/topbar";
import { TaskSheet } from "@/components/task-sheet";
import { AddArticleDialog } from "@/components/add-article-dialog";
import { useStore } from "@/lib/store";
import { useAuth } from "@/lib/auth-context";
import { supabase } from "@/lib/supabase";
import { articleRows, sheetRows, summariseByProject, type SheetRow } from "@/lib/task-sheet";
import { projectPath } from "@/lib/utils";
import { FileText } from "lucide-react";

interface StaffRow {
  id: string;
  user_id: string | null;
  email: string;
  first_name: string | null;
  last_name: string | null;
}

const authId = (s: StaffRow) => s.user_id ?? s.id;
const displayName = (s: StaffRow) =>
  [s.first_name, s.last_name].filter(Boolean).join(" ") || s.email;

/** Today in Asia/Singapore — the calendar the agency works to. */
function todayInSingapore(): string {
  return new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Singapore" });
}

export default function ArticlesPage() {
  const router = useRouter();
  const { user } = useAuth();
  const { projects } = useStore();
  const isAdmin = user?.pmRole === "admin";

  const [staff, setStaff] = useState<StaffRow[]>([]);
  const [showAdd, setShowAdd] = useState(false);
  const [clientFocus, setClientFocus] = useState<string | null>(null);
  // Hoisted: the memo below reads it and the React compiler will not accept a
  // `user?.id` dependency paired with a `user.id` read inside.
  const userId = user?.id ?? "";

  useEffect(() => {
    if (!user?.id) return;
    supabase.from("staff_members")
      .select("id,user_id,email,first_name,last_name")
      .eq("status", "active")
      .then(({ data }) => setStaff((data as StaffRow[]) ?? []));
  }, [user?.id]);

  // Staff see the articles of the projects they're staffed on — the same
  // visibility boundary as /projects and the dashboard.
  const visibleProjects = useMemo(
    () => (isAdmin ? projects : projects.filter((p) => !!userId && p.assignedStaff.includes(userId))),
    [projects, isAdmin, userId],
  );

  const rows = useMemo(() => sheetRows(visibleProjects), [visibleProjects]);
  const articles = useMemo(() => articleRows(rows), [rows]);
  const today = useMemo(() => todayInSingapore(), []);
  const byClient = useMemo(() => summariseByProject(articles, today), [articles, today]);

  const staffOptions = useMemo(
    () => staff.map((s) => ({ id: authId(s), name: displayName(s) })),
    [staff],
  );

  const projectOptions = useMemo(
    () => visibleProjects.map((p) => ({ id: p.id, name: p.name })),
    [visibleProjects],
  );

  const shown = useMemo(
    () => (clientFocus ? rows.filter((r) => r.projectId === clientFocus) : rows),
    [rows, clientFocus],
  );

  function openTask(row: SheetRow) {
    const project = projects.find((p) => p.id === row.projectId);
    if (!project) return;
    router.push(`${projectPath(project)}?task=${row.id}`);
  }

  // An article's assignee can move their own work; the admin can move anyone's.
  // An unassigned article is open, matching the task drawer's canEdit rule.
  function canEdit(row: SheetRow): boolean {
    return isAdmin || (!!userId && (row.assigneeId === userId || row.assigneeId === ""));

  }

  return (
    <>
      <Topbar title="Articles" />
      <div className="p-6 flex flex-col gap-5">
        {byClient.length > 1 && (
          <div className="flex flex-col gap-2">
            <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: "#4a7090" }}>
              Outstanding by client
            </p>
            <div className="flex gap-2 flex-wrap">
              {byClient.map((c) => {
                const active = clientFocus === c.projectId;
                const n = c.summary.outstanding;
                const color = n === 0 ? "#22c55e" : c.summary.overdue > 0 ? "#ef4444" : "#f59e0b";
                return (
                  <button
                    key={c.projectId}
                    onClick={() => setClientFocus(active ? null : c.projectId)}
                    className="flex items-center gap-2 px-3 py-2 rounded-xl text-sm transition-colors"
                    style={{
                      background: active ? "#38b6e820" : "#0f1d2e",
                      border: `1px solid ${active ? "#38b6e860" : "#1c3248"}`,
                      color: "#cce4ff",
                    }}
                    title={`${c.summary.total} article${c.summary.total !== 1 ? "s" : ""} · ${c.summary.done} done${c.summary.overdue > 0 ? ` · ${c.summary.overdue} overdue` : ""}`}
                  >
                    <span className="truncate max-w-[150px]">{c.projectName}</span>
                    <span className="font-bold tabular-nums" style={{ color }}>{n}</span>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {visibleProjects.length === 0 ? (
          <div className="text-center py-20 flex flex-col items-center gap-3">
            <FileText size={32} style={{ color: "#1c3248" }} />
            <p className="text-sm" style={{ color: "#4a7090" }}>
              You aren&apos;t staffed on any projects yet, so there are no articles to show.
            </p>
          </div>
        ) : (
          <TaskSheet
            rows={shown}
            staff={staffOptions}
            showClient
            articlesOnly
            canEdit={canEdit}
            isAdmin={isAdmin}
            onOpen={openTask}
            onAdd={() => setShowAdd(true)}
            exportName="articles"
            currentUserName={user?.name || user?.email || "Someone"}
          />
        )}
      </div>

      {showAdd && (
        <AddArticleDialog
          projectId={clientFocus}
          projects={projectOptions}
          staff={staffOptions}
          onClose={() => setShowAdd(false)}
          onCreated={() => {}}
        />
      )}
    </>
  );
}
